name: ATUkanoid Game-CI Build and Unit Tests 🎮

on:
  push: { branches: [main] }

jobs:
  testRunner:
    name: Unit Tests for ATUkanoid 🧱
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
    #Using Personal license 
    - uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        githubToken: ${{ secrets.HUBGIT_TOKEN }}  
