name: Unity Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2021.3.19f1

    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      with:
        testMode: playMode
        artifactsPath: "artifacts"
        unityVersion: 2021.3.19f1

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: artifacts
